# Generated by Django 4.2.4 on 2023-08-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('air_date', models.DateTimeField()),
                ('episodeCode', models.CharField(max_length=500, null=True)),
                ('caracteristicas', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField()),
                ('url', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200, null=True)),
                ('species', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='kauanApp.episode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='kauanApp.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='kauanApp.location')),
            ],
        ),
    ]
